version: '3.8'
services:
  db:
    image: postgres:14.4-alpine
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=public
    ports:
      - '5432:5432'
    volumes:
      - ./db:/opt
volumes:
  db:
    driver: local