version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecom
    ports:
      - '5432:5432'